# This is a basic workflow to help you get started with Actions

name: Build ElasticSearch Index

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
#  workflow_dispatch:
 #    branches:    
 #     - master  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-index:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    
#    env:
      # Environment Variables for the Indexation Script
#      ES_TEST: "elasticsearch:9200"
#      HARNESS_ACTIVE: 0
#      TEST_VERBOSE: 0

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:        
      # Start Docker Engine
#          sudo systemctl start docker
      - name: Start Docker Engine
        run: |
          sudo systemctl status docker -l
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Listing Directory Contents
        run: |
          echo 'User:' $(whoami) 
          echo 'Working Directory:' $(pwd) 
          echo 'Directory Content:' 
          ls -lah
        
      - name: Clone MetaCPAN API Project
        run: |
          mkdir -p src ; cd src
          git clone https://github.com/bodo-hugo-barwich/metacpan-api.git metacpan-api 
          cd metacpan-api
          git fetch && git checkout no-47_wrong-index && git pull && git log -1 | sed -re 's/@/ at /' | tr -s '<>'
          cd ../../

      # Build Container Images
#          sudo chmod a+w cache log perl5
      - name: Build Container Images with 'docker-compose'
        run: |
          mkdir -p cpan src ; chmod a+w cpan -R ; cd src
          git clone https://github.com/metacpan/metacpan-web.git metacpan-web
          git clone https://github.com/metacpan/metacpan-grep-front-end.git metacpan-grep-front-end
          git clone https://github.com/metacpan/metacpan-cpan-extracted-lite.git metacpan-cpan-extracted-lite
          ln -s metacpan-cpan-extracted-lite metacpan-cpan-extracted
          cd ../
          docker volume create --driver local --opt device=:$(pwd)/src/metacpan-cpan-extracted --opt o=bind --opt type=none metacpan_git_shared
          echo "Docker: Volumes listing ..."
          docker volume ls
          docker volume inspect metacpan_git_shared
          echo "Docker: Images building ..."
          docker-compose up --build --no-start traefik
          docker-compose up --build --no-start elasticsearch
          docker-compose up --build --no-start pgdb
          docker-compose up --build --no-start api
          echo "Docker: Images listing ..."
          docker image ls
          docker image inspect metacpan/metacpan-api
          echo "Docker: Volumes listing ..."
          docker volume ls
          docker volume inspect metacpan_elasticsearch
          echo "Docker: Service 'api' starting ..."
          docker-compose up -d api
          
      # Check Container Health Exit the test when Containers are failed
      - name: Check Container Health
        run: |
          constat=`docker-compose ps 2>&1` 
          echo -e "Container Status Complete:\n$constat" 
          constat=`echo "$constat" | sed -re 's/[[:space:]][[:space:]]+/|/g' | cut -d"|" -f1,3  | grep "|"`
          echo -e "Container Status Up:\n$constat"
          echo "Component 'api' Logs:"
          docker-compose logs api
          confailed=`echo "$constat" | grep -i "exit" | wc -l`
          if [ $confailed -ne 0 ]; then exit 1 ; fi
          echo "Component 'elasticsearch' Logs:"
          docker-compose logs elasticsearch
          
      # Test the Elastic Search Indexation
      - name: Run the Elastic Search Indexation
        run: |
          echo "Indexation: starting ..."
          docker-compose exec -T api index-cpan.sh
          elasticsearchport=`docker-compose ps 2>&1 | grep -i elasticsearch | grep -ioE ":[0-9]+\->" | grep -ioE "[0-9]+" | sed -n 1p`
          export ES_PORT=$elasticsearchport
          echo "ElasticSearch Port: '$ES_PORT'" 
          echo "ElasticSearch Version:" 
          curl -v "localhost:$ES_PORT" 2>&1
          echo "Indexation: Indices showing ..."
          docker-compose exec -T api curl -v 'elasticsearch:9200/_cat/indices'
          echo "Indexation: Activity Log showing ..."
          cat src/metacpan-api/var/log/metacpan.log
          doccount=`curl "localhost:$ES_PORT/_cat/indices" 2>&1 | grep -i "cpan_v1_01" | awk '{print $6}'`
          alias=`curl "localhost:$ES_PORT/_cat/aliases" 2>&1 | grep -i "cpan_v1_01" | cut -d" " -f1,2`
          if [ -z "$doccount"]; then doccount=0 ; fi
          if [ -z "$alias" ]; then alias="none" ; fi
          echo "Indexation: Document Count '$doccount'"
          echo "Indexation: Alias '$alias'"
          if [ $doccount -eq 0 ]; then exit 1 ; fi
          if [ "$alias" != "cpan cpan_v1_01" ]; then exit 1 ; fi
